;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(empty-history evil-ex-history extended-command-history))
(setq evil-ex-history '(#("w" 0 1 (ex-index 1))))
(setq extended-command-history '("eval-buffer"))
(setq evil-jumps-history '((2580 "/home/nick/.emacs.d/init.el") (2884 "/home/nick/.emacs.d/init.el") (3152 "/home/nick/.emacs.d/init.el") (670 "/home/nick/.emacs.d/init.el") (3228 "/home/nick/.emacs.d/init.el") (2743 "/home/nick/.emacs.d/init.el") (2480 "/home/nick/.emacs.d/init.el") (2077 "/home/nick/.emacs.d/init.el") (3209 "/home/nick/.emacs.d/init.el") (2743 "/home/nick/.emacs.d/init.el")))
